sounds:
- group: 0
  sound: 0
  ms: 100
- group: 0
  sound: 1
  ms: 100
- group: 0
  sound: 2
  ms: 1000
- group: 0
  sound: 3
  ms: 150
- group: 1
  sound: 0
  ms: 750
- group: 1
  sound: 1
  ms: 250
- group: 1
  sound: 2
  ms: 250
- group: 1
  sound: 3
  ms: 1750
- group: 2
  sound: 0
  ms: 1500
- group: 2
  sound: 1
  ms: 1300
- group: 2
  sound: 2
  ms: 100
- group: 2
  sound: 3
  ms: 1000
- group: 3
  sound: 0
  ms: 1000
- group: 4
  sound: 0
  ms: 2000
- group: 5
  sound: 0
  ms: 750
- group: 6
  sound: 0
  ms: 1750
- group: 7
  sound: 0
  ms: 4000
- group: 8
  sound: 0
  ms: 2750

